website/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from sqlalchemy.sql import func
from . import db

class Transactions(db.Model):
    tid = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    time = db.Column(db.DateTime(timezone=True), default=func.now())
    amt = db.Column(db.Integer)
    t_type = db.Column(db.String(10))
    username = db.Column(db.String(50))
    

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    mobile = db.Column(db.String(10), unique=True)
    password = db.Column(db.String(255))
    username = db.Column(db.String(50), unique=True)
    pin = db.Column(db.String(255))
    gender = db.Column(db.String(10))
    age = db.Column(db.Integer)
    account = db.Column(db.String(10))
    balance = db.Column(db.Float, default=0.0)
    trans = db.relationship('Transactions')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import os
from dotenv import load_dotenv

db = SQLAlchemy()

def create_app():
    load_dotenv()
    app = Flask(__name__)
    db_user = os.environ['DB_USER']
    db_pass = os.environ['DB_PASS']
    db_host = os.environ['DB_HOST']
    db_name = os.environ['DB_NAME']
    # For MySQL-compatible Aurora:
    app.config['SQLALCHEMY_DATABASE_URI'] = f"postgresql://{db_user}:{db_pass}@{db_host}:5432/{db_name}"
    db.init_app(app)
    
    from .views import views  
    from .auth import auth  
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    with app.app_context():
        db.create_all() 

    from .models import User
    
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from .models import User, db
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

@auth.route('/', methods=['GET', 'POST'])
def login():    
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('views.home'))
        else:
            flash('Invalid username or password.', category='lerror')
    
    return render_template("login.html")

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        mobile = request.form.get('mobile')
        password = request.form.get('password')
        pin = request.form.get('pin')
        age = request.form.get('age')
        gender = request.form.get('gender')
        account = request.form.get('account')

        hashedpassword = generate_password_hash(password, method='pbkdf2:sha256')
        hashedpin = generate_password_hash(pin, method='pbkdf2:sha256')

        existing_user = User.query.filter_by(mobile=mobile).first()

        if existing_user:
            flash('Mobile number is already registered for another user.', category='rerror')
        elif len(username) < 4:
            flash("Username must be greater than 4 characters.", category='rerror')
        elif len(mobile) < 10:
            flash('Mobile number must be 10 digits.', category='rerror')
        elif len(password) < 6:
            flash('Length of password should be greater than 6.', category='rerror')
        elif not password.isalnum():
            flash('Password should not contain any special characters.', category='rerror')
        elif len(pin) != 4 or not pin.isdigit():
            flash('Pin should be 4 digit long.', category='rerror')
        else:
            new_user = User(username=username, mobile=mobile, password=hashedpassword, pin=hashedpin, age=age, gender=gender, account=account)
            db.session.add(new_user)
            db.session.commit()

            flash(f'Account Successfully created! {username} is Registered!', category='rsuccess')
            return redirect(url_for('auth.login'))

    return render_template("register.html")

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import db, User, Transactions
from werkzeug.security import check_password_hash

views = Blueprint('views',__name__)

@views.route('/home')
@login_required
def home():
    return render_template('base.html', user=current_user)

@views.route('/account')
@login_required
def account():
    user = current_user
    return render_template('account.html', user=user)

@views.route('/transactions')
@login_required
def transactions():
    user = current_user
    transactions = Transactions.query.filter_by(user_id=user.id).order_by(Transactions.time.desc()).limit(10).all()
    return render_template('transactions.html', user=user, transactions=transactions)

@views.route('/')
def login():
    return render_template('login.html')

@views.route('/register')
def register():
    return render_template('register.html')

@views.route('/help')
@login_required
def help():
    return render_template('help.html')

@views.route('/faq')
@login_required
def faq():
    return render_template('faq.html')

@views.route('/plans')
@login_required
def plans():
    return render_template('plans.html')

@views.route('/withdraw', methods=['GET', 'POST'])
@login_required
def withdraw():
    if request.method == 'POST':
        amount = float(request.form.get('withdraw'))
        pin = request.form.get('pin')

        if not check_password_hash(current_user.pin, pin):
            flash('Invalid PIN. Please try again.', category='werror')
        elif current_user.balance < amount:
            flash('Insufficient balance.', category='werror')
        else:
            current_user.balance -= amount
            new_transaction = Transactions(user_id=current_user.id, amt=amount, t_type='withdraw', username=current_user.username)
            db.session.add(new_transaction)
            db.session.commit()
            flash('Withdrawal successful.', category='wsuccess')
            # return redirect(url_for('views.transactions'))

    return render_template('withdraw.html')

@views.route('/deposit', methods=['GET', 'POST'])
@login_required
def deposit():
    if request.method == 'POST':
        amount = float(request.form.get('deposit'))
        pin = request.form.get('pin')

        if not check_password_hash(current_user.pin, pin):
            flash('Invalid PIN. Please try again.', category='derror')
        else:
            current_user.balance += amount
            new_transaction = Transactions(user_id=current_user.id, amt=amount, t_type='deposit', username=current_user.username)
            db.session.add(new_transaction)
            db.session.commit()
            flash('Deposit successful.', category='dsuccess')
            # return redirect(url_for('views.transactions'))

    return render_template('deposit.html')

@views.route('/transfer', methods=['GET', 'POST'])
@login_required
def transfer():
    if request.method == 'POST':
        amount = float(request.form.get('transfer'))
        to_user_id = request.form.get('toid')
        pin = request.form.get('pin')

        recipient = User.query.filter_by(id=to_user_id).first()

        if not recipient:
            flash('Recipient account does not exist.', category='terror')
        elif not check_password_hash(current_user.pin, pin):
            flash('Invalid PIN. Please try again.', category='terror')
        elif current_user.balance < amount:
            flash('Insufficient balance.', category='terror')
        else:
            current_user.balance -= amount
            recipient.balance += amount
            new_transaction = Transactions(user_id=current_user.id, amt=amount, t_type='transfer', username=current_user.username)
            db.session.add(new_transaction)
            recipient_transaction = Transactions(user_id=recipient.id, amt=amount, t_type='receive', username=recipient.username)
            db.session.add(recipient_transaction)
            db.session.commit()
            flash('Transfer successful.', category='tsuccess')
            # return redirect(url_for('views.transactions'))
    
    return render_template('transfer.html')

website/templates/account.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/acc.css') }}">
    <title>Account</title>
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>

    <main>
        <section class="account-details">
            <h2>Account Details</h2><br><br>
            <div class="account-info">
                <p><strong>Username:</strong> {{ user.username }}</p>
                <p><strong>Mobile:</strong> {{ user.mobile }}</p>
                <p><strong>Gender:</strong> {{ user.gender }}</p>
                <p><strong>Age:</strong> {{ user.age }}</p>
                <p><strong>Account Type:</strong> {{ user.account }}</p>
                <p><strong>Balance:</strong> {{ user.balance }}</p> 
            </div>
            
        </section>
    </main>
    <footer>
    <p>&copy; The Piggy Bank 2024</p>
    </footer>
</body>
</html>

website/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <title>Home</title>
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>

    <main>
        <section class="help-section">
            <div class="help-item">
                <img src="{{url_for('static', filename='bal.jpg')}}" alt="balance">
                <h2>View Balance</h2>
                <p>Get a quick look: See your current balance and latest transactions at a glance.</p>
                <a href="{{ url_for('views.transactions') }}">View Balance</a>
            </div>
            <div class="help-item">
                <img src="{{url_for('static', filename='trans.jpg')}}" alt="d/w money">
                <h2>Transact Money</h2>
                <p>Manage your money: Easily deposit, withdraw, transfer funds.</p>
                <a href="{{ url_for('views.deposit') }}">&#x2022; Deposit Money</a><br><br>
                <a href="{{ url_for('views.withdraw') }}">&#x2022; Withdraw Money</a><br><br>
                <a href="{{ url_for('views.transfer') }}">&#x2022; Transfer Money</a>
            </div>
        </section>

        <section class="contact-section">
            <div class="contact-item">
                <img src="{{url_for('static', filename='acc.jpg')}}" alt="account">
                <h2>Account Details</h2>
                <p>Know your account: View your account number, type, and holder information.</p>
                <a href="{{ url_for('views.account') }}">View Account Details</a>
            </div>
            <div class="contact-item">
                <img src="{{url_for('static', filename='plan.jpg')}}" alt="rates">
                <h2>Rates & Plans</h2>
                <p>Do not Miss! See current interest rates and plans.</p>
                <a href="{{ url_for('views.plans') }}">View Rates & Plans</a>
            </div>
        </section>
    </main>
    <footer>
    <p>&copy; The Piggy Bank 2024</p>
</footer>
</body>
</html>

website/templates/deposit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <title>Deposit Money</title>
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>

    <main>
        <div class="login-form">
            <h1>Deposit Money!</h1>
            <form action="{{ url_for('views.deposit') }}" method="POST">
                  <input type="number" placeholder="Amount to be depositted" name="deposit" required>
              <br> <br><input type="password" placeholder="Enter Pin" name="pin" required>
              <br><br><button type="submit">Deposit Money</button><br><br>
              <a href="{{ url_for('views.transactions') }}">View Latest Transactions</a>
            </form>
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                {% if category == 'derror' %}
                    <div class="alert alert-danger alert-dismissible show" role="alert">
                        {{ "Alert: "+ message }}
                    </div>
                {% elif category == 'dsuccess' %}
                    <div class="alert alert-success alert-dismissible show" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
                {% endfor %}
            {% endif %}
            {% endwith %}
          </div> 
    </main>
    <footer>
    <p>&copy; The Piggy Bank 2024</p>
</footer>
</body>
</html>

website/templates/faq.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FAQs</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/faq.css') }}">
    <title>Home</title>
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>
  <h1>Frequently Asked Questions</h1>
  <div class="faq-container">

    <div class="faq-item">
      <div class="faq-question">
        <p>1. What types of accounts do you offer?</p>
      </div>
      <div class="faq-answer">
        <p>Most banks offer a variety of accounts to suit different needs, 
            such as checking accounts for everyday transactions, savings accounts for 
            building your nest egg, and money market accounts for earning a little interest on your savings.</p>
      </div>
    </div>

    <div class="faq-item">
        <div class="faq-question">
          <p>2. What are my ATM options?</p>
        </div>
        <div class="faq-answer">
          <p>Many banks offer access to a network of ATMs where you can withdraw cash and make deposits. You may be charged fees for using ATMs outside your bank's network.

          </p>
        </div>
    </div>

    <div class="faq-item">
        <div class="faq-question">
          <p>3. How do I use online banking?</p>
        </div>
        <div class="faq-answer">
          <p>Most banks offer online banking, which allows you to view your account balance, transfer funds, and pay bills electronically. You'll need to enroll for online banking and create a secure login.
        </p>
        </div>
    </div>

    <div class="faq-item">
        <div class="faq-question">
          <p>4. What are debit and credit cards?</p>
        </div>
        <div class="faq-answer">
          <p>Debit cards deduct money directly from your checking account when you make a purchase. Credit cards allow you to borrow money from the bank to make purchases, and you'll need to repay the balance each month to avoid interest charges.</p>
        </div>
    </div>

    <div class="faq-item">
        <div class="faq-question">
          <p>5. What are bank fees?</p>
        </div>
        <div class="faq-answer">
          <p>Banks may charge fees for various services, such as monthly account maintenance, ATM withdrawals, and overdrafts. It's important to understand your bank's fee schedule before opening an account. </p>
        </div>
    </div>

    <div class="faq-item">
        <div class="faq-question">
          <p>6. How do I keep my account safe?</p>
        </div>
        <div class="faq-answer">
          <p>Here are some tips:<br>

            * Memorize your PIN and don't share it with anyone. <br>
            * Beware of phishing scams - don't click on suspicious links or attachments in emails or texts.<br>
            * Review your bank statements regularly and report any unauthorized transactions immediately.</p>
        </div>
    </div>

    </div>
  <p class="last">Still have questions? Contact our customer support team at [phone number].</p>
<footer>
    <p>&copy; The Piggy Bank 2024</p>
</footer>
</body>
</html>

website/templates/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Help & Contact Us</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/help.css') }}">
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}"> Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>
    
    <main>
        <section class="help-section">
            <div class="help-item">
                <img src="{{url_for('static', filename='faq.png')}}" alt="FAQ">
            </div>
            <div class="help-content">
                <h2> Frequently Asked Questions</h2>
                <p> Find answers to common questions about our products, services, and banking.</p>
                <a href="{{ url_for('views.faq') }}">View FAQs</a>
            </div>
        </section>

        <section class="contact-section">
            <div class="contact-item">
                <img src="{{url_for('static', filename='cs.webp')}}" alt="Phone">
            </div>
            <div class="contact-content">
                <h2> Phone Banking</h2>
                <p> Call us at 123456789 to speak with a customer service representative.</p>
            </div>
        </section>

        </main>
        <footer>
            <p>&copy; The Piggy Bank 2024</p>
        </footer>
</body>
</html>

website/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/login.css') }}"
    />
    <title>Login</title>
  </head>
  <body>
    <nav class="navbar">
      <div class="navdiv">
        <div class="logo"><p>The Piggy Bank</p></div>
      </div>
    </nav>

    <main>
      <div class="login-form">
        <h1>Welcome to The Piggy Bank!!!</h1>
        <form method="POST" action="{{ url_for('auth.login') }}">
          <input type="text" placeholder="Username" name="username" required />
          <br /><br />
          <input
            type="password"
            placeholder="Password"
            name="password"
            required
          />
          <br /><br />
          <button type="submit">Login</button>
          <br /><br />
          <a href="{{ url_for('views.register') }}">New User? Register</a>
        </form>
        {% with messages = get_flashed_messages(with_categories=True) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'lerror' %}
        <div class="alert alert-danger alert-dismissible show" role="alert">
          {{ message }}
        </div>
        {% elif category == 'lsuccess' %}
        <div class="alert alert-success alert-dismissible show" role="alert">
          {{ message }}
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
      </div>
    </main>
    <footer>
      <p>&copy; The Piggy Bank 2024</p>
    </footer>
  </body>
</html>

website/templates/plans.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plans</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/plans.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}"> Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>
    
    <main>
        <section class="help-section">
            <div class="help-item">
                <img src="{{url_for('static', filename='p5.jpg')}}" alt="FAQ">
            </div>
            <div class="help-content">
                <h2> Grow Your Savings & Get Rewarded Daily</h2>
                <p>Discover high-yield Savings Accounts & feature-rich Checking Accounts that work for you.</p>
            </div>
        </section>

        <section class="contact-section">
            
            <div class="contact-content">
                <h2> Savings Accounts:</h2>
                <p> 
                    Basic Savings: No monthly fee, minimum balance requirement $25, interest rate 0.75% APY
                <br> High-Interest Savings: $7 monthly fee, minimum balance requirement $10,000, interest rate 2.25% APY
                </p>
            </div>
            <div class="contact-item">
                <img src="{{url_for('static', filename='p1.jpg')}}" alt="Phone">
            </div>
        </section>

        <section class="help-section">
            <div class="help-item">
                <img src="{{url_for('static', filename='p3.jpg')}}" alt="FAQ">
            </div>
            <div class="help-content">
                <h2> Checking Accounts:</h2>
                <p> 
                    Everyday Checking: $5 monthly fee, up to 100 free transactions per month, interest rate 0.25% APY
                <br>Premium Checking: $15 monthly fee, unlimited transactions, free ATM rebates, interest rate 0.50% APY
                </p>
            </div>
        </section>

        <section class="contact-section">
            
            <div class="contact-content">
                <h2> Loans: </h2>
                <p> 
                    Auto Loan: New car loan starting at 3.75% APR, used car loan starting at 4.50% APR
                <br>Mortgage: 30-year fixed-rate mortgage starting at 5.25% APR, 15-year fixed-rate mortgage starting at 4.75% APR
                </p>
            </div>
            <div class="contact-item">
                <img src="{{url_for('static', filename='p2.jpg')}}" alt="Phone">
            </div>
        </section>

        <section class="help-section">
            <div class="help-item">
                <img src="{{url_for('static', filename='p4.jpg')}}" alt="FAQ">
            </div>
            <div class="help-content">
                <h2> Current Accounts: </h2>
                <p> 
                    Basic Current Account: $0 monthly fee, unlimited deposits and withdrawals
                <br>Premium Current Account: $10 monthly fee, additional benefits like check printing, bill pay services
                </p>
            </div>
        </section>
        </main>
        <footer>
            <p>&copy; The Piggy Bank 2024</p>
        </footer>
</body>
</html>

website/templates/transfer.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <title>Transfer Money</title>
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>

    <main>
        <div class="login-form">
            <h1>Transfer Money!</h1>
            <form action="{{ url_for('views.transfer') }}" method="POST">
                 <input type="number" placeholder="Amount to be transfered" name="transfer" required>
              <br> <br><input type="text" placeholder="Account to be transfered to" name="toid" required>
              <br> <br><input type="password" placeholder="Enter Pin" name="pin" required>
              <br><br><button type="submit">Transfer Money</button>
            </form>
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                {% if category == 'terror' %}
                    <div class="alert alert-danger alert-dismissible show" role="alert">
                        {{ "Alert: "+ message }}
                    </div>
                {% elif category == 'tsuccess' %}
                    <div class="alert alert-success alert-dismissible show" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
                {% endfor %}
            {% endif %}
            {% endwith %}
          </div> 
    </main>
    <footer>
    <p>&copy; The Piggy Bank 2024</p>
</footer>
</body>
</html>

website/templates/withdraw.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <title>Withdraw Money</title>
</head>
<body>
    <nav class="navbar">
        <div class="navdiv">
            <div class="logo"><p>The Piggy Bank</p></div>
        <ul>
            <li><a href="{{ url_for('views.home') }}">Home</a></li>
            <li><a href="{{ url_for('views.account') }}">Account</a></li>
            <li><a href="{{ url_for('views.transactions') }}">Transactions</a></li>
            <li><a href="{{ url_for('views.plans') }}">Plans</a></li>
            <li><a href="{{ url_for('views.help') }}">Help</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li> 
        </ul>
        </div>
    </nav>

    <main>
        <div class="login-form">
            <h1>Withdraw Money!</h1>
            <form action="{{ url_for('views.withdraw') }}" method="POST"> 
                <input type="number" placeholder="Amount to be withdrawn" name="withdraw" required>
              <br> <br><input type="password" placeholder="Enter Pin" name="pin" required>
              <br><br><button type="submit">Withdraw Money</button><br><br>
              <a href="{{ url_for('views.transactions') }}">View Latest Transactions</a>
            </form>
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                {% if category == 'werror' %}
                    <div class="alert alert-danger alert-dismissible show" role="alert">
                        {{ "Alert: "+ message }}
                    </div>
                {% elif category == 'wsuccess' %}
                    <div class="alert alert-success alert-dismissible show" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
                {% endfor %}
            {% endif %}
            {% endwith %}
          </div> 
    </main>
    <footer>
    <p>&copy; The Piggy Bank 2024</p>
</footer>
</body>
</html>